# Generated by Django 4.2.7 on 2023-11-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craevedenie', '0002_image_blocknature_blockhistory_blockculture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockculture',
            name='images',
            field=models.ManyToManyField(blank=True, to='craevedenie.image'),
        ),
        migrations.AlterField(
            model_name='blockhistory',
            name='images',
            field=models.ManyToManyField(blank=True, to='craevedenie.image'),
        ),
        migrations.AlterField(
            model_name='blocknature',
            name='images',
            field=models.ManyToManyField(blank=True, to='craevedenie.image'),
        ),
    ]
