# Generated by Django 4.2.7 on 2023-11-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craevedenie', '0004_remove_blockculture_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockculture',
            name='images',
        ),
        migrations.RemoveField(
            model_name='blockhistory',
            name='images',
        ),
        migrations.RemoveField(
            model_name='blocknature',
            name='images',
        ),
        migrations.AddField(
            model_name='blockculture',
            name='images',
            field=models.ManyToManyField(blank=True, to='craevedenie.image'),
        ),
        migrations.AddField(
            model_name='blockhistory',
            name='images',
            field=models.ManyToManyField(blank=True, to='craevedenie.image'),
        ),
        migrations.AddField(
            model_name='blocknature',
            name='images',
            field=models.ManyToManyField(blank=True, to='craevedenie.image'),
        ),
    ]
