# Generated by Django 4.2.7 on 2023-11-26 18:04

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('craevedenie', '0005_remove_blockculture_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockculture',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='blockhistory',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='blocknature',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
