# Generated by Django 4.2.7 on 2023-11-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craevedenie', '0006_alter_blockculture_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockculture',
            name='images',
        ),
        migrations.RemoveField(
            model_name='blockhistory',
            name='images',
        ),
        migrations.RemoveField(
            model_name='blocknature',
            name='images',
        ),
        migrations.AddField(
            model_name='blockculture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='block_culture'),
        ),
        migrations.AddField(
            model_name='blockhistory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='block_history'),
        ),
        migrations.AddField(
            model_name='blocknature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='block_nature'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
