# Generated by Django 4.2.7 on 2023-11-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craevedenie', '0007_remove_blockculture_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockculture',
            name='link_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
