# Generated by Django 4.2.7 on 2023-11-27 08:09

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('craevedenie', '0008_blockculture_link_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockMonument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', tinymce.models.HTMLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='block_monument')),
                ('link_image', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
